import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import StyledButton from "~/components/Button";

import { api } from "~/utils/api";

export default function Signup() {
  return (
    <>
      <Head>
        <title>Sign Up</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="p-5 hover:opacity-75">
        <Link href="/">
          <Image src="/assets/logo.png" alt="header" width={65} height={65} />
        </Link>
      </div>
      {/* Adjusted div for centering text */}
      <div
        className="flex items-start justify-center"
        style={{ height: "100vh" }}
      >
        <div className="text-center" style={{ marginTop: "5%" }}>
          <div className="h2 text-darkBlue">Let's Get Started</div>
          <div
            className="flex-col items-start justify-between space-y-6"
            style={{ marginTop: "5%" }}
          >
            <Link href="/login?role=teacher">
              <StyledButton
                label="I'm a Teacher"
                colorInd={1}
                onClick={() => { }}
                style={{
                  width: "50%",
                  paddingTop: "15px",
                  paddingBottom: "15px",
                  marginBottom: "3%",
                }}
              />
            </Link>
            <Link href="/login?role=student">
              <StyledButton
                label="I'm a Student"
                colorInd={2}
                onClick={() => { }}
                style={{
                  width: "50%",
                  paddingTop: "15px",
                  paddingBottom: "15px",
                  marginBottom: "3%",
                }}
              />
            </Link>
          </div>
        </div>
      </div>
    </>
  );
}
